# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('phoneno', models.IntegerField()),
                ('datetime', models.DateTimeField(unique=True)),
                ('guestcount', models.SmallIntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Upcoming reservation'), (1, 'Guest is here'), (2, 'Guest has left'), (3, 'Guest missed reservation')], default=0)),
                ('occasion', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
