# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='hotelname',
            field=models.CharField(default='The Ritz', max_length=30),
            preserve_default=False,
        ),
    ]
