# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_status_last_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set([('datetime', 'hotelname')]),
        ),
    ]
